# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: availability.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'availability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61vailability.proto\x12\x0c\x61vailability\"\"\n\rDoctorRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\x05\"(\n\rSlotsResponse\x12\x17\n\x0f\x61vailable_slots\x18\x01 \x03(\t2d\n\x13\x41vailabilityService\x12M\n\x11GetAvailableSlots\x12\x1b.availability.DoctorRequest\x1a\x1b.availability.SlotsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'availability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCTORREQUEST']._serialized_start=36
  _globals['_DOCTORREQUEST']._serialized_end=70
  _globals['_SLOTSRESPONSE']._serialized_start=72
  _globals['_SLOTSRESPONSE']._serialized_end=112
  _globals['_AVAILABILITYSERVICE']._serialized_start=114
  _globals['_AVAILABILITYSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
